### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jhi2** [ynkdir/py-win32more#58]
Hwere is the code:https://pastebin.com/u/jhi2/1/t2JyPYBh
Here is the error:
```
Traceback (most recent call last):
  File "c:\Users\johnd\source\repos\PyUi3\PyUI3\test.py", line 4, in <module>
    window = PyUI3.ApplicationWindow()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\PyUI3\__init__.py", line 37, in __init__
    self.app = App()
               ^^^^^
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\PyUI3\__init__.py", line 28, in __init__       
    super().__init__()
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\win32more\xaml.py", line 29, in __init__       
    super().__init__(own=True)
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\win32more\_winrt.py", line 1063, in __init__   
    self._inner = self._compose()
                  ^^^^^^^^^^^^^^^
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\win32more\_winrt.py", line 1105, in _compose   
    base.CreateInstance(self, inner)
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\win32more\_winrt.py", line 739, in __call__    
    factory = _ro_get_activation_factory(cls._classid_, factory_class)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johnd\AppData\Roaming\Python\Python312\site-packages\win32more\_winrt.py", line 811, in _ro_get_activation_factory
    raise WinError(hr)
OSError: [WinError -2147221164] Class not registered
```

**Comment by jhi2** [comment]
Please help me

**Comment by ynkdir** [comment]
I'm afraid I can't help you.
