### ISSUE TITLE
How to create custom object?

### ISSUE THREAD

**Issue by moi15moi** [ynkdir/py-win32more#80]
How can we implement custom COM objects?

For example, I tried to implement [IDWriteFontCollectionLoader](https://learn.microsoft.com/en-us/windows/win32/api/dwrite/nn-dwrite-idwritefontcollectionloader) like this (I overrride the ``CreateEnumeratorFromKey`` method):
```py
from ctypes import byref, POINTER
from win32more import VoidPtr, UInt32
from win32more.Windows.Win32.Foundation import HRESULT, S_OK
from win32more.Windows.Win32.Graphics.DirectWrite import (
    DWRITE_FACTORY_TYPE_ISOLATED,
    DWriteCreateFactory,
    IDWriteFactory,
    IDWriteFontCollectionLoader,
    IDWriteFontFileEnumerator,
)


class CustomFontCollectionLoader(IDWriteFontCollectionLoader):

    def __init__(self):
        super(CustomFontCollectionLoader, self).__init__()

    def CreateEnumeratorFromKey(
            self,
            this: IDWriteFontCollectionLoader,
            factory: IDWriteFactory,
            collectionKey: VoidPtr,
            collectionKeySize: UInt32,
            fontFileEnumerator: POINTER(IDWriteFontFileEnumerator)
        )-> HRESULT:

        return S_OK


dwrite_factory = IDWriteFactory(own=True)
hr = DWriteCreateFactory(DWRITE_FACTORY_TYPE_ISOLATED, dwrite_factory._iid_, byref(dwrite_factory))

font_collection_loader = CustomFontCollectionLoader()
dwrite_factory.RegisterFontCollectionLoader(byref(font_collection_loader))
```
But, I get this exception, so I tought this wasn't the way to do it:
```py
Traceback (most recent call last):
  File "c:\Users\moi15moi\Desktop\win32more test.py", line 34, in <module>
    dwrite_factory.RegisterFontCollectionLoader(byref(font_collection_loader))
  File "c:\Users\moi15moi\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32more\__init__.py", line 451, in __call__
    return self._delegate(this, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\moi15moi\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32more\__init__.py", line 468, in __call__
    result = self._delegate(this, *cargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000008
```

**Comment by ynkdir** [comment]
Try win32more._winrt.ComClass.  ComClass is an utility to define custom com class.


```python
# ComClass usage
class MyComClass(ComClass, Interface1, Interface2, ...):
    # You need to implement methods of Interface1, Interface2 and etc....
    # ComClass has default implementation of IUnknown and IInspectable.
    ...
```

```python
from ctypes import byref, POINTER
from win32more import VoidPtr, UInt32
from win32more.Windows.Win32.Foundation import HRESULT, S_OK
from win32more.Windows.Win32.Graphics.DirectWrite import (
    DWRITE_FACTORY_TYPE_ISOLATED,
    DWriteCreateFactory,
    IDWriteFactory,
    IDWriteFontCollectionLoader,
    IDWriteFontFileEnumerator,
)

from win32more._winrt import ComClass

class CustomFontCollectionLoader(ComClass, IDWriteFontCollectionLoader):

    def __init__(self):
        super(CustomFontCollectionLoader, self).__init__()

    def CreateEnumeratorFromKey(
            self,
            # this: IDWriteFontCollectionLoader,  <- not needed
            factory: IDWriteFactory,
            collectionKey: VoidPtr,
            collectionKeySize: UInt32,
            fontFileEnumerator: POINTER(IDWriteFontFileEnumerator)
        )-> HRESULT:

        return S_OK


dwrite_factory = IDWriteFactory(own=True)
hr = DWriteCreateFactory(DWRITE_FACTORY_TYPE_ISOLATED, dwrite_factory._iid_, byref(dwrite_factory))
assert hr == 0

font_collection_loader = CustomFontCollectionLoader()

# No need to use byref()
hr = dwrite_factory.RegisterFontCollectionLoader(font_collection_loader)
assert hr == 0
```

Note that win32more's com class is actually a com pointer.

```python
# Python
p = IUnknown()
```

is equivalent to

```c
// C
IUnknown *p;
```

**Comment by moi15moi** [comment]
Thanks!
